url= "https://sourcevault.github.io/resume"
relativeURLs = true
EnableIRI = true
languageCode = "en-us"
title = "> RESUME"
theme = "researcher"
canonifyURLs = true
[menu]
  [[menu.main]]
    name = "Github"
    url = 'https://github.com/sourcevault'
    weight = 1
  [[menu.main]]
    name = "Twitter"
    url = 'https://twitter.com/sourcevault_pub'
    weight = 2
  [[menu.main]]
    name = "Email"
    url = "mailto:sourcevault_pub@gmail.com"
    weight = 3
  [[menu.main]]
    name = "CV.PDF"
    url = "CV.pdf"
  # [[menu.main]]
  #   name = "ÑƒĞºÑ€Ğ°Ğ¸Ğ½ĞµÑ†"
  #   url = "./ukraine"
  # [[menu.main]]
  #   name = "english"
  #   url = "about"

    # 'pre' and 'post' hooks are available
    # here we use an icon from Bootstrap https://icons.getbootstrap.com/
    # pre = '<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-file-earmark-person-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M2 2a2 2 0 0 1 2-2h5.293A1 1 0 0 1 10 .293L13.707 4a1 1 0 0 1 .293.707V14a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2zm7.5 1.5v-2l3 3h-2a1 1 0 0 1-1-1zM11 8a3 3 0 1 1-6 0 3 3 0 0 1 6 0zm2 5.755S12 12 8 12s-5 1.755-5 1.755V14a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1v-.245z"/></svg> '
    weight = 4
[params]
  author = "Joy Krishna Mondal"
  favicon = "favicon.ico"  # path to a .ico to use as favicon
  [params.footer]
    text = "ğŸ‘‹ğŸ¼ GOOD DAY | SchÃ¶nen Tag |  à¦§à¦¨à§à¦¯à¦¬à¦¾à¦¦ | bonne journÃ©e | à¤§à¤¨à¥à¤¯à¤µà¤¾à¤¦ | buen dÃ­a | å†è§  | ÑĞ¿Ğ°ÑĞ¸Ğ±Ğ¾ | ÙˆØ´ÙƒØ± "
